// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	models "github.com/nirajgeorgian/gateway/src/models"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// create an account
type CreateAccountReq struct {
	Account              *models.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateAccountReq) Reset()         { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()    {}
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CreateAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReq.Unmarshal(m, b)
}
func (m *CreateAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReq.Marshal(b, m, deterministic)
}
func (m *CreateAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReq.Merge(m, src)
}
func (m *CreateAccountReq) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReq.Size(m)
}
func (m *CreateAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReq proto.InternalMessageInfo

func (m *CreateAccountReq) GetAccount() *models.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateAccountRes struct {
	Account              *models.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateAccountRes) Reset()         { *m = CreateAccountRes{} }
func (m *CreateAccountRes) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRes) ProtoMessage()    {}
func (*CreateAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CreateAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRes.Unmarshal(m, b)
}
func (m *CreateAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRes.Marshal(b, m, deterministic)
}
func (m *CreateAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRes.Merge(m, src)
}
func (m *CreateAccountRes) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRes.Size(m)
}
func (m *CreateAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRes proto.InternalMessageInfo

func (m *CreateAccountRes) GetAccount() *models.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// read an account
type ReadAccountReq struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountReq) Reset()         { *m = ReadAccountReq{} }
func (m *ReadAccountReq) String() string { return proto.CompactTextString(m) }
func (*ReadAccountReq) ProtoMessage()    {}
func (*ReadAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ReadAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountReq.Unmarshal(m, b)
}
func (m *ReadAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountReq.Marshal(b, m, deterministic)
}
func (m *ReadAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountReq.Merge(m, src)
}
func (m *ReadAccountReq) XXX_Size() int {
	return xxx_messageInfo_ReadAccountReq.Size(m)
}
func (m *ReadAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountReq proto.InternalMessageInfo

func (m *ReadAccountReq) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type ReadAccountRes struct {
	Account              *models.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReadAccountRes) Reset()         { *m = ReadAccountRes{} }
func (m *ReadAccountRes) String() string { return proto.CompactTextString(m) }
func (*ReadAccountRes) ProtoMessage()    {}
func (*ReadAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *ReadAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountRes.Unmarshal(m, b)
}
func (m *ReadAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountRes.Marshal(b, m, deterministic)
}
func (m *ReadAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountRes.Merge(m, src)
}
func (m *ReadAccountRes) XXX_Size() int {
	return xxx_messageInfo_ReadAccountRes.Size(m)
}
func (m *ReadAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountRes proto.InternalMessageInfo

func (m *ReadAccountRes) GetAccount() *models.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// update an account
type UpdateAccountReq struct {
	Account              *models.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateAccountReq) Reset()         { *m = UpdateAccountReq{} }
func (m *UpdateAccountReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountReq) ProtoMessage()    {}
func (*UpdateAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *UpdateAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountReq.Unmarshal(m, b)
}
func (m *UpdateAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountReq.Marshal(b, m, deterministic)
}
func (m *UpdateAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountReq.Merge(m, src)
}
func (m *UpdateAccountReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountReq.Size(m)
}
func (m *UpdateAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountReq proto.InternalMessageInfo

func (m *UpdateAccountReq) GetAccount() *models.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateAccountRes struct {
	Success              bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Account              *models.Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateAccountRes) Reset()         { *m = UpdateAccountRes{} }
func (m *UpdateAccountRes) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRes) ProtoMessage()    {}
func (*UpdateAccountRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *UpdateAccountRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRes.Unmarshal(m, b)
}
func (m *UpdateAccountRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRes.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRes.Merge(m, src)
}
func (m *UpdateAccountRes) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRes.Size(m)
}
func (m *UpdateAccountRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRes proto.InternalMessageInfo

func (m *UpdateAccountRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateAccountRes) GetAccount() *models.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// auth for account
type AuthReq struct {
	Account              *models.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetAccount() *models.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type AuthRes struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRes) Reset()         { *m = AuthRes{} }
func (m *AuthRes) String() string { return proto.CompactTextString(m) }
func (*AuthRes) ProtoMessage()    {}
func (*AuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *AuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRes.Unmarshal(m, b)
}
func (m *AuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRes.Marshal(b, m, deterministic)
}
func (m *AuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRes.Merge(m, src)
}
func (m *AuthRes) XXX_Size() int {
	return xxx_messageInfo_AuthRes.Size(m)
}
func (m *AuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRes proto.InternalMessageInfo

func (m *AuthRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthRes) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

// validate username
type ValidateUsernameReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateUsernameReq) Reset()         { *m = ValidateUsernameReq{} }
func (m *ValidateUsernameReq) String() string { return proto.CompactTextString(m) }
func (*ValidateUsernameReq) ProtoMessage()    {}
func (*ValidateUsernameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *ValidateUsernameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateUsernameReq.Unmarshal(m, b)
}
func (m *ValidateUsernameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateUsernameReq.Marshal(b, m, deterministic)
}
func (m *ValidateUsernameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateUsernameReq.Merge(m, src)
}
func (m *ValidateUsernameReq) XXX_Size() int {
	return xxx_messageInfo_ValidateUsernameReq.Size(m)
}
func (m *ValidateUsernameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateUsernameReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateUsernameReq proto.InternalMessageInfo

func (m *ValidateUsernameReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ValidateUsernameRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateUsernameRes) Reset()         { *m = ValidateUsernameRes{} }
func (m *ValidateUsernameRes) String() string { return proto.CompactTextString(m) }
func (*ValidateUsernameRes) ProtoMessage()    {}
func (*ValidateUsernameRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *ValidateUsernameRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateUsernameRes.Unmarshal(m, b)
}
func (m *ValidateUsernameRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateUsernameRes.Marshal(b, m, deterministic)
}
func (m *ValidateUsernameRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateUsernameRes.Merge(m, src)
}
func (m *ValidateUsernameRes) XXX_Size() int {
	return xxx_messageInfo_ValidateUsernameRes.Size(m)
}
func (m *ValidateUsernameRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateUsernameRes.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateUsernameRes proto.InternalMessageInfo

func (m *ValidateUsernameRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// validate email
type ValidateEmailReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEmailReq) Reset()         { *m = ValidateEmailReq{} }
func (m *ValidateEmailReq) String() string { return proto.CompactTextString(m) }
func (*ValidateEmailReq) ProtoMessage()    {}
func (*ValidateEmailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *ValidateEmailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEmailReq.Unmarshal(m, b)
}
func (m *ValidateEmailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEmailReq.Marshal(b, m, deterministic)
}
func (m *ValidateEmailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEmailReq.Merge(m, src)
}
func (m *ValidateEmailReq) XXX_Size() int {
	return xxx_messageInfo_ValidateEmailReq.Size(m)
}
func (m *ValidateEmailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEmailReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEmailReq proto.InternalMessageInfo

func (m *ValidateEmailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ValidateEmailRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEmailRes) Reset()         { *m = ValidateEmailRes{} }
func (m *ValidateEmailRes) String() string { return proto.CompactTextString(m) }
func (*ValidateEmailRes) ProtoMessage()    {}
func (*ValidateEmailRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ValidateEmailRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEmailRes.Unmarshal(m, b)
}
func (m *ValidateEmailRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEmailRes.Marshal(b, m, deterministic)
}
func (m *ValidateEmailRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEmailRes.Merge(m, src)
}
func (m *ValidateEmailRes) XXX_Size() int {
	return xxx_messageInfo_ValidateEmailRes.Size(m)
}
func (m *ValidateEmailRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEmailRes.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEmailRes proto.InternalMessageInfo

func (m *ValidateEmailRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

//  --------------- Job api --------------------
type CreateJobReq struct {
	Job                  *models.Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateJobReq) Reset()         { *m = CreateJobReq{} }
func (m *CreateJobReq) String() string { return proto.CompactTextString(m) }
func (*CreateJobReq) ProtoMessage()    {}
func (*CreateJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *CreateJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobReq.Unmarshal(m, b)
}
func (m *CreateJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobReq.Marshal(b, m, deterministic)
}
func (m *CreateJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobReq.Merge(m, src)
}
func (m *CreateJobReq) XXX_Size() int {
	return xxx_messageInfo_CreateJobReq.Size(m)
}
func (m *CreateJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobReq proto.InternalMessageInfo

func (m *CreateJobReq) GetJob() *models.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type CreateJobRes struct {
	Job                  *models.Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateJobRes) Reset()         { *m = CreateJobRes{} }
func (m *CreateJobRes) String() string { return proto.CompactTextString(m) }
func (*CreateJobRes) ProtoMessage()    {}
func (*CreateJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *CreateJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRes.Unmarshal(m, b)
}
func (m *CreateJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRes.Marshal(b, m, deterministic)
}
func (m *CreateJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRes.Merge(m, src)
}
func (m *CreateJobRes) XXX_Size() int {
	return xxx_messageInfo_CreateJobRes.Size(m)
}
func (m *CreateJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRes proto.InternalMessageInfo

func (m *CreateJobRes) GetJob() *models.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

// --------------- main api --------------------------
type ConfirmationRes struct {
	Status               bool     `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationRes) Reset()         { *m = ConfirmationRes{} }
func (m *ConfirmationRes) String() string { return proto.CompactTextString(m) }
func (*ConfirmationRes) ProtoMessage()    {}
func (*ConfirmationRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *ConfirmationRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationRes.Unmarshal(m, b)
}
func (m *ConfirmationRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationRes.Marshal(b, m, deterministic)
}
func (m *ConfirmationRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationRes.Merge(m, src)
}
func (m *ConfirmationRes) XXX_Size() int {
	return xxx_messageInfo_ConfirmationRes.Size(m)
}
func (m *ConfirmationRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationRes.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationRes proto.InternalMessageInfo

func (m *ConfirmationRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type AccountConfirmationReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,3,opt,name=ConfirmationCode,proto3" json:"ConfirmationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountConfirmationReq) Reset()         { *m = AccountConfirmationReq{} }
func (m *AccountConfirmationReq) String() string { return proto.CompactTextString(m) }
func (*AccountConfirmationReq) ProtoMessage()    {}
func (*AccountConfirmationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *AccountConfirmationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountConfirmationReq.Unmarshal(m, b)
}
func (m *AccountConfirmationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountConfirmationReq.Marshal(b, m, deterministic)
}
func (m *AccountConfirmationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountConfirmationReq.Merge(m, src)
}
func (m *AccountConfirmationReq) XXX_Size() int {
	return xxx_messageInfo_AccountConfirmationReq.Size(m)
}
func (m *AccountConfirmationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountConfirmationReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountConfirmationReq proto.InternalMessageInfo

func (m *AccountConfirmationReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountConfirmationReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AccountConfirmationReq) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAccountReq)(nil), "account.CreateAccountReq")
	proto.RegisterType((*CreateAccountRes)(nil), "account.CreateAccountRes")
	proto.RegisterType((*ReadAccountReq)(nil), "account.ReadAccountReq")
	proto.RegisterType((*ReadAccountRes)(nil), "account.ReadAccountRes")
	proto.RegisterType((*UpdateAccountReq)(nil), "account.UpdateAccountReq")
	proto.RegisterType((*UpdateAccountRes)(nil), "account.UpdateAccountRes")
	proto.RegisterType((*AuthReq)(nil), "account.AuthReq")
	proto.RegisterType((*AuthRes)(nil), "account.AuthRes")
	proto.RegisterType((*ValidateUsernameReq)(nil), "account.ValidateUsernameReq")
	proto.RegisterType((*ValidateUsernameRes)(nil), "account.ValidateUsernameRes")
	proto.RegisterType((*ValidateEmailReq)(nil), "account.ValidateEmailReq")
	proto.RegisterType((*ValidateEmailRes)(nil), "account.ValidateEmailRes")
	proto.RegisterType((*CreateJobReq)(nil), "account.CreateJobReq")
	proto.RegisterType((*CreateJobRes)(nil), "account.CreateJobRes")
	proto.RegisterType((*ConfirmationRes)(nil), "account.ConfirmationRes")
	proto.RegisterType((*AccountConfirmationReq)(nil), "account.AccountConfirmationReq")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x5e, 0x7f, 0xfd, 0x6d, 0x6d, 0x4f, 0xbb, 0x51, 0x99, 0xb1, 0x95, 0x08, 0x06, 0xca, 0xd5,
	0x98, 0x4a, 0x23, 0x8a, 0xb8, 0x1a, 0x42, 0x2a, 0x15, 0x9a, 0x36, 0x69, 0x12, 0x4a, 0xd5, 0x09,
	0x71, 0x83, 0x9c, 0xc4, 0xcd, 0x3c, 0xda, 0xb8, 0xc4, 0xce, 0x10, 0x3c, 0x14, 0xcf, 0xc0, 0xbb,
	0xf0, 0x22, 0xc8, 0x8e, 0x9d, 0x25, 0xe9, 0x9f, 0xa9, 0xdc, 0xe5, 0xf3, 0x39, 0xdf, 0xe7, 0x73,
	0x8e, 0xbf, 0xd3, 0x42, 0x03, 0xcf, 0x69, 0x6f, 0x1e, 0x33, 0xc1, 0x50, 0x0d, 0xfb, 0x3e, 0x4b,
	0x22, 0x61, 0xbd, 0x0c, 0xa9, 0xb8, 0x4e, 0xbc, 0x9e, 0xcf, 0x66, 0x4e, 0xc8, 0x42, 0xe6, 0xa8,
	0xb8, 0x97, 0x4c, 0x14, 0x52, 0x40, 0x7d, 0xa5, 0x3c, 0xab, 0x39, 0x63, 0x01, 0x99, 0xa6, 0xc0,
	0x7e, 0x07, 0xed, 0x61, 0x4c, 0xb0, 0x20, 0x83, 0x54, 0xcc, 0x25, 0xdf, 0xd0, 0x09, 0x18, 0xe9,
	0x4e, 0xe5, 0x79, 0xe5, 0xb8, 0xd9, 0x6f, 0xf7, 0x34, 0xee, 0x99, 0x2c, 0x93, 0xb0, 0x84, 0xcf,
	0x37, 0xe2, 0x3b, 0xb0, 0xe7, 0x12, 0x1c, 0xe4, 0x6e, 0x7f, 0x0a, 0xa0, 0x83, 0x5f, 0x68, 0xa0,
	0x04, 0x1a, 0x6e, 0x43, 0x9f, 0x9c, 0x07, 0xf6, 0xdb, 0x12, 0x81, 0x6f, 0x5a, 0xee, 0x78, 0x1e,
	0xfc, 0x7b, 0xbb, 0x9f, 0x16, 0xf8, 0x1c, 0x75, 0xa0, 0xc6, 0x13, 0xdf, 0x27, 0x9c, 0x2b, 0x7e,
	0xdd, 0x35, 0x30, 0xaf, 0xfc, 0xdf, 0x7d, 0xca, 0x6f, 0xa0, 0x36, 0x48, 0xc4, 0xf5, 0xa6, 0x05,
	0x65, 0x34, 0x8e, 0xf6, 0x61, 0x5b, 0xb0, 0xaf, 0x24, 0xd2, 0x33, 0x4b, 0x81, 0x3c, 0xbd, 0xc5,
	0x53, 0x1a, 0xa8, 0x0a, 0xea, 0x6e, 0x0a, 0xec, 0x57, 0xf0, 0xf0, 0x4a, 0x7e, 0x60, 0x41, 0xc6,
	0x9c, 0xc4, 0x11, 0x9e, 0x11, 0x79, 0xb3, 0x05, 0xf5, 0x44, 0x43, 0xad, 0x92, 0x61, 0xdb, 0x59,
	0x46, 0x59, 0xd3, 0xbd, 0x7d, 0x0c, 0x6d, 0x43, 0xf8, 0x30, 0xc3, 0x74, 0x2a, 0x2f, 0xd8, 0x87,
	0x6d, 0x22, 0xbf, 0x4d, 0x8d, 0x0a, 0xd8, 0xdd, 0x85, 0xcc, 0x75, 0xba, 0x3d, 0x68, 0xa5, 0x96,
	0xbb, 0x60, 0x9e, 0xd4, 0x3c, 0x82, 0xea, 0x0d, 0xf3, 0xf4, 0xa8, 0x5a, 0xd9, 0xa8, 0x64, 0x54,
	0x06, 0x4a, 0xf9, 0xfc, 0xde, 0xfc, 0x17, 0xf0, 0x60, 0xc8, 0xa2, 0x09, 0x8d, 0x67, 0x58, 0x50,
	0x16, 0x49, 0xca, 0x01, 0xec, 0x8c, 0x04, 0x16, 0x89, 0xa9, 0x45, 0x23, 0xfb, 0x27, 0x1c, 0xe8,
	0x17, 0x29, 0x32, 0xd4, 0x24, 0xc7, 0xa5, 0x49, 0x1a, 0x2c, 0x5b, 0xbb, 0x24, 0x9c, 0xe3, 0x90,
	0xa8, 0x47, 0x69, 0xb8, 0x06, 0xa2, 0x13, 0x68, 0xe7, 0x85, 0x86, 0x2c, 0x20, 0x9d, 0xaa, 0x4a,
	0x59, 0x38, 0xef, 0xff, 0xaa, 0xc2, 0x9e, 0xbe, 0x7c, 0x44, 0xe2, 0x5b, 0xea, 0x13, 0x74, 0x06,
	0xbb, 0x85, 0x65, 0x44, 0x8f, 0xb3, 0xee, 0xca, 0x4b, 0x6e, 0xad, 0x0c, 0x71, 0x7b, 0x0b, 0x0d,
	0xa0, 0x99, 0x5b, 0x32, 0x74, 0x98, 0xe5, 0x16, 0x77, 0xd5, 0x5a, 0x11, 0x90, 0x12, 0x67, 0xb0,
	0x5b, 0xd8, 0x94, 0x5c, 0x2d, 0xe5, 0x0d, 0xb4, 0x56, 0x86, 0xa4, 0x50, 0x17, 0xfe, 0x97, 0x0e,
	0x47, 0xb9, 0x25, 0x48, 0xf7, 0xc4, 0x2a, 0x9f, 0xc8, 0xec, 0x8f, 0x77, 0x56, 0xca, 0xe6, 0xfd,
	0x24, 0xcb, 0x5b, 0xe2, 0x79, 0x6b, 0x5d, 0x54, 0x37, 0x52, 0x30, 0x67, 0xae, 0x91, 0xb2, 0xbd,
	0xad, 0x95, 0x21, 0x6e, 0x6f, 0xf5, 0xcf, 0x01, 0x2e, 0x98, 0x67, 0xde, 0xea, 0x14, 0x1a, 0x99,
	0x2b, 0xd1, 0xa3, 0xd2, 0x63, 0xa4, 0xce, 0xb6, 0x96, 0x1e, 0x4b, 0xa9, 0x09, 0xb4, 0x2e, 0x31,
	0x9d, 0x72, 0x23, 0x76, 0x05, 0x87, 0x23, 0x12, 0x05, 0x4b, 0xbc, 0x88, 0x9e, 0x95, 0x7f, 0x3b,
	0x4a, 0x4e, 0xb5, 0x3a, 0x77, 0x97, 0x14, 0x5d, 0x6f, 0x6f, 0xbd, 0xef, 0xff, 0xfe, 0x73, 0x54,
	0xf9, 0xdc, 0xcd, 0xfd, 0xbf, 0x44, 0x34, 0xc6, 0x37, 0x21, 0x61, 0x71, 0x48, 0x71, 0xe4, 0x84,
	0x58, 0x90, 0xef, 0xf8, 0x87, 0xc3, 0x63, 0xdf, 0xc1, 0x73, 0x7a, 0x8a, 0xe7, 0xd4, 0xdb, 0x51,
	0x7f, 0x2c, 0xaf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x89, 0x54, 0x78, 0xaa, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRes, error)
	ReadAccount(ctx context.Context, in *ReadAccountReq, opts ...grpc.CallOption) (*ReadAccountRes, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountReq, opts ...grpc.CallOption) (*UpdateAccountRes, error)
	Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error)
	ValidateUsername(ctx context.Context, in *ValidateUsernameReq, opts ...grpc.CallOption) (*ValidateUsernameRes, error)
	ValidateEmail(ctx context.Context, in *ValidateEmailReq, opts ...grpc.CallOption) (*ValidateEmailRes, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountRes, error) {
	out := new(CreateAccountRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ReadAccount(ctx context.Context, in *ReadAccountReq, opts ...grpc.CallOption) (*ReadAccountRes, error) {
	out := new(ReadAccountRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/ReadAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateAccount(ctx context.Context, in *UpdateAccountReq, opts ...grpc.CallOption) (*UpdateAccountRes, error) {
	out := new(UpdateAccountRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error) {
	out := new(AuthRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ValidateUsername(ctx context.Context, in *ValidateUsernameReq, opts ...grpc.CallOption) (*ValidateUsernameRes, error) {
	out := new(ValidateUsernameRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/ValidateUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ValidateEmail(ctx context.Context, in *ValidateEmailReq, opts ...grpc.CallOption) (*ValidateEmailRes, error) {
	out := new(ValidateEmailRes)
	err := c.cc.Invoke(ctx, "/account.AccountService/ValidateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	CreateAccount(context.Context, *CreateAccountReq) (*CreateAccountRes, error)
	ReadAccount(context.Context, *ReadAccountReq) (*ReadAccountRes, error)
	UpdateAccount(context.Context, *UpdateAccountReq) (*UpdateAccountRes, error)
	Auth(context.Context, *AuthReq) (*AuthRes, error)
	ValidateUsername(context.Context, *ValidateUsernameReq) (*ValidateUsernameRes, error)
	ValidateEmail(context.Context, *ValidateEmailReq) (*ValidateEmailRes, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ReadAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ReadAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/ReadAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ReadAccount(ctx, req.(*ReadAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateAccount(ctx, req.(*UpdateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Auth(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ValidateUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ValidateUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/ValidateUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ValidateUsername(ctx, req.(*ValidateUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ValidateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ValidateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/ValidateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ValidateEmail(ctx, req.(*ValidateEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
		{
			MethodName: "ReadAccount",
			Handler:    _AccountService_ReadAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AccountService_UpdateAccount_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _AccountService_Auth_Handler,
		},
		{
			MethodName: "ValidateUsername",
			Handler:    _AccountService_ValidateUsername_Handler,
		},
		{
			MethodName: "ValidateEmail",
			Handler:    _AccountService_ValidateEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error) {
	out := new(CreateJobRes)
	err := c.cc.Invoke(ctx, "/account.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	CreateJob(context.Context, *CreateJobReq) (*CreateJobRes, error)
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// MailsServiceClient is the client API for MailsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailsServiceClient interface {
	SendAccountConfirmation(ctx context.Context, in *AccountConfirmationReq, opts ...grpc.CallOption) (*ConfirmationRes, error)
}

type mailsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMailsServiceClient(cc *grpc.ClientConn) MailsServiceClient {
	return &mailsServiceClient{cc}
}

func (c *mailsServiceClient) SendAccountConfirmation(ctx context.Context, in *AccountConfirmationReq, opts ...grpc.CallOption) (*ConfirmationRes, error) {
	out := new(ConfirmationRes)
	err := c.cc.Invoke(ctx, "/account.MailsService/SendAccountConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailsServiceServer is the server API for MailsService service.
type MailsServiceServer interface {
	SendAccountConfirmation(context.Context, *AccountConfirmationReq) (*ConfirmationRes, error)
}

func RegisterMailsServiceServer(s *grpc.Server, srv MailsServiceServer) {
	s.RegisterService(&_MailsService_serviceDesc, srv)
}

func _MailsService_SendAccountConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountConfirmationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailsServiceServer).SendAccountConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.MailsService/SendAccountConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailsServiceServer).SendAccountConfirmation(ctx, req.(*AccountConfirmationReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.MailsService",
	HandlerType: (*MailsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAccountConfirmation",
			Handler:    _MailsService_SendAccountConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
