// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mails/api.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// --------------- main api --------------------------
type ConfirmationRes struct {
	Status               bool     `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationRes) Reset()         { *m = ConfirmationRes{} }
func (m *ConfirmationRes) String() string { return proto.CompactTextString(m) }
func (*ConfirmationRes) ProtoMessage()    {}
func (*ConfirmationRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ad4510bd1f3a8d, []int{0}
}

func (m *ConfirmationRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationRes.Unmarshal(m, b)
}
func (m *ConfirmationRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationRes.Marshal(b, m, deterministic)
}
func (m *ConfirmationRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationRes.Merge(m, src)
}
func (m *ConfirmationRes) XXX_Size() int {
	return xxx_messageInfo_ConfirmationRes.Size(m)
}
func (m *ConfirmationRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationRes.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationRes proto.InternalMessageInfo

func (m *ConfirmationRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type AccountConfirmationReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,3,opt,name=ConfirmationCode,proto3" json:"ConfirmationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountConfirmationReq) Reset()         { *m = AccountConfirmationReq{} }
func (m *AccountConfirmationReq) String() string { return proto.CompactTextString(m) }
func (*AccountConfirmationReq) ProtoMessage()    {}
func (*AccountConfirmationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ad4510bd1f3a8d, []int{1}
}

func (m *AccountConfirmationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountConfirmationReq.Unmarshal(m, b)
}
func (m *AccountConfirmationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountConfirmationReq.Marshal(b, m, deterministic)
}
func (m *AccountConfirmationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountConfirmationReq.Merge(m, src)
}
func (m *AccountConfirmationReq) XXX_Size() int {
	return xxx_messageInfo_AccountConfirmationReq.Size(m)
}
func (m *AccountConfirmationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountConfirmationReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountConfirmationReq proto.InternalMessageInfo

func (m *AccountConfirmationReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountConfirmationReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AccountConfirmationReq) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

func init() {
	proto.RegisterType((*ConfirmationRes)(nil), "mails.ConfirmationRes")
	proto.RegisterType((*AccountConfirmationReq)(nil), "mails.AccountConfirmationReq")
}

func init() { proto.RegisterFile("mails/api.proto", fileDescriptor_34ad4510bd1f3a8d) }

var fileDescriptor_34ad4510bd1f3a8d = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0x62, 0xad, 0x8b, 0x50, 0xd9, 0x43, 0x0c, 0x01, 0x45, 0x72, 0x52, 0xc1, 0x2c,
	0xd4, 0x8b, 0xe0, 0x49, 0x7b, 0xee, 0x25, 0xc1, 0x8b, 0xb7, 0xc9, 0x76, 0xba, 0xae, 0x98, 0x9d,
	0xb8, 0xbb, 0x51, 0xf4, 0xd7, 0xf9, 0x5f, 0xfc, 0x23, 0xe2, 0x58, 0x4b, 0xd5, 0xde, 0xf6, 0x9b,
	0xb7, 0x6f, 0x98, 0xf7, 0xc4, 0xa8, 0x05, 0xfb, 0x18, 0x14, 0x74, 0xb6, 0xec, 0x3c, 0x45, 0x92,
	0xdb, 0x3c, 0xc8, 0xcf, 0x8d, 0x8d, 0xf7, 0x7d, 0x53, 0x6a, 0x6a, 0x95, 0x21, 0x43, 0x8a, 0xd5,
	0xa6, 0x9f, 0x33, 0x31, 0xf0, 0xeb, 0xdb, 0x55, 0x9c, 0x8a, 0xd1, 0x84, 0xdc, 0xdc, 0xfa, 0x16,
	0xa2, 0x25, 0x57, 0x61, 0x90, 0xa9, 0x18, 0xd4, 0x11, 0x62, 0x1f, 0xb2, 0xe4, 0x38, 0x39, 0x19,
	0x56, 0x0b, 0x2a, 0xde, 0x44, 0x7a, 0xad, 0x35, 0xf5, 0x2e, 0xfe, 0x76, 0x3c, 0xc9, 0x5c, 0x0c,
	0x6f, 0x03, 0x7a, 0x07, 0x2d, 0xb2, 0x67, 0xb7, 0x5a, 0xb2, 0xcc, 0xc4, 0xce, 0x14, 0x43, 0x00,
	0x83, 0xd9, 0x26, 0x4b, 0x3f, 0x28, 0xcf, 0xc4, 0xfe, 0xea, 0xa2, 0x09, 0xcd, 0x30, 0xdb, 0xe2,
	0x2f, 0xff, 0xe6, 0xe3, 0x46, 0xec, 0x4d, 0xbf, 0xe2, 0xd5, 0xe8, 0x9f, 0xad, 0x46, 0x59, 0x89,
	0x83, 0x1a, 0xdd, 0x6c, 0xcd, 0x3d, 0xf2, 0xb0, 0xe4, 0x22, 0xca, 0xf5, 0xb7, 0xe6, 0xe9, 0x42,
	0xfe, 0x93, 0xba, 0xd8, 0xb8, 0xb9, 0x7c, 0xff, 0x38, 0x4a, 0xee, 0xc6, 0x2b, 0xfd, 0x39, 0xeb,
	0xe1, 0xc1, 0x20, 0x79, 0x63, 0xc1, 0x29, 0x03, 0x11, 0x5f, 0xe0, 0x55, 0x05, 0xaf, 0xd5, 0xb2,
	0xfc, 0x2b, 0xe8, 0x6c, 0x33, 0xe0, 0x2e, 0x2f, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x63,
	0x3a, 0x32, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MailsServiceClient is the client API for MailsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailsServiceClient interface {
	SendAccountConfirmation(ctx context.Context, in *AccountConfirmationReq, opts ...grpc.CallOption) (*ConfirmationRes, error)
}

type mailsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMailsServiceClient(cc *grpc.ClientConn) MailsServiceClient {
	return &mailsServiceClient{cc}
}

func (c *mailsServiceClient) SendAccountConfirmation(ctx context.Context, in *AccountConfirmationReq, opts ...grpc.CallOption) (*ConfirmationRes, error) {
	out := new(ConfirmationRes)
	err := c.cc.Invoke(ctx, "/mails.MailsService/SendAccountConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailsServiceServer is the server API for MailsService service.
type MailsServiceServer interface {
	SendAccountConfirmation(context.Context, *AccountConfirmationReq) (*ConfirmationRes, error)
}

func RegisterMailsServiceServer(s *grpc.Server, srv MailsServiceServer) {
	s.RegisterService(&_MailsService_serviceDesc, srv)
}

func _MailsService_SendAccountConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountConfirmationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailsServiceServer).SendAccountConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mails.MailsService/SendAccountConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailsServiceServer).SendAccountConfirmation(ctx, req.(*AccountConfirmationReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mails.MailsService",
	HandlerType: (*MailsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAccountConfirmation",
			Handler:    _MailsService_SendAccountConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mails/api.proto",
}
