// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AuthReq struct {
	Email        *string `json:"Email"`
	PasswordHash *string `json:"PasswordHash"`
}

type AuthRes struct {
	Token *string `json:"Token"`
	Valid *bool   `json:"Valid"`
}

type CreateAccountReq struct {
	Email        string `json:"Email"`
	Username     string `json:"Username"`
	Description  string `json:"Description"`
	PasswordHash string `json:"PasswordHash"`
}
