// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateAccountReq struct {
	Email       *string `json:"Email"`
	Username    *string `json:"Username"`
	Description *string `json:"Description"`
	Password    *string `json:"Password"`
}

type CreateJobReq struct {
	JobID   *string `json:"job_id"`
	JobName *string `json:"job_name"`
}
